### ISSUE TITLE
Upgrade to NserviceBus 7.3 from 6.5.2 causes "Could not extract 'scannedTypes' field from EndpointConfiguration."

### ISSUE THREAD

**Issue by miguelqvd** [NServiceBusExtensions/NServiceBus.HandlerOrdering#109]
After upgrading our Visual Studio solution from NServiceBus 6.5.2 to 7.3 we get the error from below.  Removing             endpointConfiguration.ApplyInterfaceHandlerOrdering(); removes the problem, but, of course is not what we need...

 System.Exception. ExceptionMessage : Could not extract 'scannedTypes' field from EndpointConfiguration. Raise an issue here https://github.com/NServiceBusExtensions/HandlerOrdering/issues/new, Exception trace is: System.Exception: Could not extract 'scannedTypes' field from EndpointConfiguration. Raise an issue here https://github.com/NServiceBusExtensions/HandlerOrdering/issues/new
   at OrderHandlers.GetHandlerDependencies(EndpointConfiguration endpointConfiguration)
   at OrderHandlers.ApplyInterfaceHandlerOrdering(EndpointConfiguration endpointConfiguration)
   at OrderHandlers.Customize(EndpointConfiguration configuration)
   at NServiceBus.EndpointConfiguration.<FinalizeConfiguration>b__14_0(INeedInitialization t)
   at NServiceBus.EndpointConfiguration.<>c__DisplayClass17_0`1.<ActivateAndInvoke>b__0(Type t)
   at NServiceBus.EndpointConfiguration.ForAllTypes[T](IEnumerable`1 types, Action`1 action)
   at NServiceBus.EndpointConfiguration.ActivateAndInvoke[T](IList`1 types, Action`1 action)
   at NServiceBus.EndpointConfiguration.FinalizeConfiguration(List`1 availableTypes)
   at NServiceBus.HostCreator.<CreateWithInternallyManagedContainer>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Endpoint.<Start>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by miguelqvd** [comment]
It turns out that the max compatible version of NServiceBus with your HandlerOrdering is 7.1.13

**Comment by SimonCropp** [comment]
yep. a breaking change in nservicebus means this is no longer possible. u need to raise with them if u still need this feature 

btw you should be paying to use any extension under this organisation https://github.com/NServiceBusExtensions/Home/#licensingpatron-faq

**Comment by miguelqvd** [comment]
Thank you for your response. I will raise the licensing issue and I will come back to you. However, it may take a few weeks as everybody is on summer holidays.
